smartmind-team/thanosql-docs

- docs/tutorial_template.md
> 이전 다음 update

- README.md
- docs/how-to_guides/ThanoSQL_connecting/data_upload.md
- docs/how-to_guides/modelling/LIST_SYNTAX.md
- docs/how-to_guides/modelling/OPTIONS.md
- docs/how-to_guides/thanosql_api/rest_api_thanosql_insert.md
- docs/how-to_guides/thanosql_api/rest_api_thanosql_query.md
- docs/how-to_guides/thanosql_api/rest_api_thanosql_search.md
- docs/how-to_guides/thanosql_api/rest_api_token.md
- docs/quick_start/how_to_use_ThanoSQL.md
- docs/tutorials/thanosql_ml/audio_recognition/audio_recognition_wav2vec.md
- docs/tutorials/thanosql_ml/classification/automl_classification.md
- docs/tutorials/thanosql_ml/classification/classification_Electra.md
- docs/tutorials/thanosql_ml/classification/classification_convNext.md
- docs/tutorials/thanosql_ml/recommendation/recommendation_lfm.md
- docs/tutorials/thanosql_ml/regression/automl_regression.md
- docs/tutorials/thanosql_search/image_search/clip_image_search.md
- docs/tutorials/thanosql_search/image_search/select_image_query.md
- docs/tutorials/thanosql_search/image_search/simclr_image_search.md
추가적으로 오타 수정했습니다 
[수정 전] TAHNOSQL MODEL 
[수정 후] THANOSQL MODEL
> 6/1 PR 복원 및 반영 

- docs/tutorials/thanosql_ml/audio_recognition/audio_recognition_wav2vec.md
- docs/tutorials/thanosql_ml/classification/automl_classification.md
- docs/tutorials/thanosql_ml/classification/classification_Electra.md
- docs/tutorials/thanosql_ml/classification/classification_convNext.md
- docs/tutorials/thanosql_ml/recommendation/recommendation_lfm.md
- docs/tutorials/thanosql_ml/regression/automl_regression.md
- docs/tutorials/thanosql_search/image_search/clip_image_search.md
- docs/tutorials/thanosql_search/image_search/select_image_query.md
- docs/tutorials/thanosql_search/image_search/simclr_image_search.md
- 데이터 세트 준비 수정 
- [이미지로 이미지 검색하기] 설명에서는 35322.jpg 실행 단계에서는 1.jpg로 다른 사진을 이용하는 것처럼 보임  : 반영 완료 2022.06.08
부대표님 점검 완료
> Click up 수정 내용 반영

- docs/quick_start/how_to_use_ThanoSQL.md
- docs/tutorials/thanosql_ml/audio_recognition/audio_recognition_wav2vec.md
- docs/tutorials/thanosql_ml/classification/automl_classification.md
- docs/tutorials/thanosql_ml/classification/classification_Electra.md
- docs/tutorials/thanosql_ml/classification/classification_convNext.md
- docs/tutorials/thanosql_ml/recommendation/recommendation_lfm.md
- docs/tutorials/thanosql_ml/regression/automl_regression.md
- docs/tutorials/thanosql_search/image_search/clip_image_search.md
- docs/tutorials/thanosql_search/image_search/select_image_query.md
- docs/tutorials/thanosql_search/image_search/simclr_image_search.md
문서 수정 
주요 commit 내용 
- API_token Guide ( {} -> <> & 랜딩페이지 위치 조정) 
- AutoML classification 시간 변경 (기존 : 30 -> 300)
> Hotfix tutorial : docs 

- mkdocs.yml
https://app.clickup.com/t/2uamcr8
footer에 회사 정보 및 copyright 추가
> 결함 8 : 제품 지원 정보 미제공 (구조 관련 내용)

- .gitignore
- docs/en/tutorials/thanosql_ml/audio_recognition/audio_recognition_wav2vec.md
- docs/en/tutorials/thanosql_ml/classification/automl_classification.md
- docs/en/tutorials/thanosql_ml/classification/classification_Electra.md
- docs/en/tutorials/thanosql_ml/classification/classification_convNext.md
- docs/en/tutorials/thanosql_ml/regression/automl_regression.md
- docs/en/tutorials/thanosql_search/image_search/clip_image_search.md
- docs/en/tutorials/thanosql_search/image_search/select_image_query.md
- docs/en/tutorials/thanosql_search/image_search/simclr_image_search.md
- Tutorial 타이틀 번역 수정
- File Location 수정
> Edit Tutorial Title and File Location

- docs/ko/how-to_guides/ThanoSQL_query/.pages
- docs/ko/how-to_guides/ThanoSQL_query/CREATE_TABLE_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_query/GET_SYNTAX.md
- docs/ko/how-to_guides/syntax_list.md
> Created new syntax page: GET

- Pipfile
- Pipfile.lock
- mkdocs.yml
- overrides/main.html
- requirements.txt
- delete requirements.txt & add pipfile (+ pipfile.lock)
- add mkdocs-jupyter
- add download button for notebook files
- change jupyter a tag color (match with md a tag)
- add navigation.tracking
> Docs & Tutorial Sync + mkdocs setting

- docs/en/how-to_guides/ThanoSQL_query/.pages
- docs/en/how-to_guides/ThanoSQL_query/GET_SYNTAX.md
- docs/en/how-to_guides/ThanoSQL_query/UPLOAD_SYNTAX.md
GET & UPLOAD syntax 영문 버전 입니다.
> Update: english version for GET and UPLOAD syntax

- docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_query.md
- docs/ko/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_query.md
Content-Type이 빠져있어서 수정했습니다 
```
-H 'Content-Type: application/json' \
```
> fix: Content-Type added

- docs/en/how-to_guides/ThanoSQL_query/.pages
- docs/en/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
- docs/en/how-to_guides/reference.md
- docs/ko/how-to_guides/ThanoSQL_query/.pages
- docs/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
- docs/ko/how-to_guides/reference.md
> Cu 35ruwca copy statement docs 

- docs/en/how-to_guides/ThanoSQL_query/SEARCH_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_query/SEARCH_SYNTAX.md
> search syntax error fix

- docs/en/getting_started/data_upload.md
- docs/en/getting_started/hello_ThanoSQL.md
- docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_query.md
- docs/en/index.md
> fix: correct grammatical error

- docs/en/getting_started/hello_ThanoSQL.md
- docs/en/getting_started/how_to_use_ThanoSQL.md
- docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_search.md
- docs/en/how-to_guides/ThanoSQL_query/BUILD_MODEL_SYNTAX.md
- docs/en/how-to_guides/ThanoSQL_query/CONVERT_USING_SYNTAX.md
- docs/en/how-to_guides/ThanoSQL_query/EVALUATE_MODEL_SYNTAX.md
- docs/en/how-to_guides/ThanoSQL_query/FIT_MODEL_SYNTAX.md
- docs/en/how-to_guides/ThanoSQL_query/PREDICT_MODEL_SYNTAX.md
- docs/en/how-to_guides/ThanoSQL_query/SEARCH_SYNTAX.md
- docs/en/how-to_guides/ThanoSQL_query/TRANSFORM_MODEL_SYNTAX.md
- docs/en/how-to_guides/reference.md
- docs/en/index.md
- docs/en/tutorials/algorithm_list.md
- docs/ko/how-to_guides/reference.md
1. "the" ThanoSQL ____
2. ThanoSQL database -> ThanoSQL Workspace Database
3. 영문 제목 대문자
> fix: general grammar fixes

- docs/en/how-to_guides/ThanoSQL_query/GET_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_query/GET_SYNTAX.md
1. GET syntax update for en & ko
> update: GET syntax

- docs/en/how-to_guides/ThanoSQL_model/CLIP.md
- docs/en/how-to_guides/ThanoSQL_model/SBERT.md
- docs/en/how-to_guides/ThanoSQL_model/SimCLR.md
- docs/en/how-to_guides/ThanoSQL_query/PRINT_SYNTAX.md
- docs/en/how-to_guides/ThanoSQL_query/SEARCH_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_model/CLIP.md
- docs/ko/how-to_guides/ThanoSQL_model/SBERT.md
- docs/ko/how-to_guides/ThanoSQL_model/SimCLR.md
- docs/ko/how-to_guides/ThanoSQL_query/PRINT_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_query/SEARCH_SYNTAX.md
1. SEARCH clause syntax change and other files that use SEARCH
> update: SEARCH syntax

- docs/en/FAQ/frequently_asked_question.md
- docs/ko/FAQ/frequently_asked_question.md
__답변 내용__ 
➡️  ThanoSQL에서는 "%"를 이스케이프문으로 받아들이기 때문에, "%%" 라고 작성해야합니다.
> FAQ: "%" operator doesn'work (answer added)

- templates/function_statement_template.md
- templates/function_statement_template_ko.md
- templates/model_statement_template.md
- templates/model_statement_template_ko.md
- templates/thanosql_statement_template.md
- templates/thanosql_statement_template_ko.md
Docs Function, Statement, Model 템플릿(한/영) 추가
> docs: upload templates

- docs/ko/how-to_guides/ThanoSQL_model/Albert_Electra.md
- docs/ko/how-to_guides/ThanoSQL_model/AutomlClassifier.md
- docs/ko/how-to_guides/ThanoSQL_model/AutomlRegressor.md
- docs/ko/how-to_guides/ThanoSQL_model/ConvNeXt_EfficientNet.md
- docs/ko/how-to_guides/ThanoSQL_model/SBERT.md
- docs/ko/how-to_guides/ThanoSQL_model/SimCLR.md
- docs/ko/how-to_guides/ThanoSQL_model/Wav2Vec2.md
- docs/ko/how-to_guides/ThanoSQL_query/BUILD_MODEL_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_query/FIT_MODEL_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_query/GET_SYNTAX.md
- docs/ko/how-to_guides/ThanoSQL_query/UPLOAD_MODEL_SYNTAX.md
- docs/ko/tutorials/thanosql_ml/audio_recognition/speech_recognition.md
- docs/ko/tutorials/thanosql_ml/audio_recognition/speech_recognition2.md
- docs/ko/tutorials/thanosql_ml/classification/automl_classification.md
- docs/ko/tutorials/thanosql_ml/classification/image_classification.md
- docs/ko/tutorials/thanosql_ml/classification/text_classification.md
- docs/ko/tutorials/thanosql_ml/question_answering/visual_question_answering.md
- docs/ko/tutorials/thanosql_ml/regression/automl_regression.md
- docs/ko/tutorials/thanosql_ml/udm_tutorial.md
- docs/ko/tutorials/thanosql_search/search_image_by_image.md
- docs/ko/tutorials/thanosql_search/search_image_by_keyword.md
- docs/ko/tutorials/thanosql_search/search_image_by_text.md
- docs/ko/tutorials/thanosql_search/search_text_by_text.md
- templates/model_statement_template_ko.md
- templates/thanosql_statement_template_ko.md
> hotfix: update overwrite description 가능 유무 -> 가능 여부

- docs/en/how-to_guides/ThanoSQL_function/Compute.md
- docs/en/how-to_guides/ThanoSQL_model/CLIP.md
- docs/en/how-to_guides/ThanoSQL_model/SBERT.md
- docs/en/how-to_guides/ThanoSQL_model/SimCLR.md
- docs/en/how-to_guides/ThanoSQL_model/XCLIP.md
- docs/ko/how-to_guides/ThanoSQL_function/Compute.md
- docs/ko/how-to_guides/ThanoSQL_model/CLIP.md
- docs/ko/how-to_guides/ThanoSQL_model/SBERT.md
- docs/ko/how-to_guides/ThanoSQL_model/SimCLR.md
- docs/ko/how-to_guides/ThanoSQL_model/XCLIP.md
> feat: use top_k for search

- docs/en/tutorials/thanosql_ml/classification/automl_classification.ipynb
- docs/en/tutorials/thanosql_ml/classification/image_classification.ipynb
- docs/en/tutorials/thanosql_ml/regression/automl_regression.ipynb
- docs/ko/tutorials/thanosql_ml/classification/automl_classification.ipynb
- docs/ko/tutorials/thanosql_ml/regression/automl_regression.ipynb
- docs/ko/tutorials/thanosql_search/search_image_by_keyword.ipynb
> Hot-fix: tutorial conflict resolved

- mkdocs.yml
> chore: add Timeseries korean title

- docs/en/FAQ/frequently_asked_question.md
- docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_query.md
- docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_search.md
- docs/ko/FAQ/frequently_asked_question.md
- docs/ko/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_query.md
Related to [ThanoSQL Engine PR](https://github.com/smartmind-team/thanosql-engine/pull/195)
Explanation about byte columns being encoded added. 
> update: explanation about encoding and decoding bytes added

- docs/en/index.md
- docs/ko/index.md
1. 이전에 삭제했던 포맷인 시간과 수정 날짜를 intro에서도 삭제해줬습니다.
2. 개요 페이지에서 카드 섹션의 순서만 변경하였습니다.
~추후에 AutoCRM과 Query Everything 내용이 추가되면 카드도 같이 추가해야 합니다.~
> fix: change order for card in intro page

- docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_query.md
- docs/ko/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_query.md
Hotfix: Adding description of destination schema to query API
> hotfix: adding destination schema
